version: '3.4'

services:
  # DB
  paperless-db:
    container_name: paperless-db
    image: postgres:latest
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - paperless-network
    restart: unless-stopped
  
  # REST service
  paperless-rest:
    container_name: paperless-rest
    build:
      context: .
      dockerfile: Paperless.REST/Dockerfile
    ports:
      - 8081:8081
    networks:
      - paperless-network
    restart: unless-stopped
    depends_on:
      - paperless-db

  # WebUI service
  paperless-frontend:
    container_name: paperless-frontend
    image: nginx:latest
    volumes:
      - ./Paperless.Frontend:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - paperless-network
    restart: unless-stopped
    depends_on:
      - paperless-rest
    
networks:
    paperless-network:
        driver: bridge
        
volumes:
  db-data:
